version: '3.5'

networks: 
  localdev:
    name: localdev

services:
  viewnextwebapi:
    image: viewnextwebapi
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - localdev
    restart: always
    ports:
      - "7000:80"
      - "7001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=credentials
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
  db-server:
    image: sqlserver
    build:
      context: .
      dockerfile: sqlserver.Dockerfile
    volumes:
      - ./data:/var/opt/mssql/data 
    ports:
      - "1433:1433"
    networks: 
      - localdev

