version: '3.5'

networks: 
  localdev:
    name: localdev

services:
  viewnextwebapi:
    image: viewnextwebapi
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - localdev
    restart: always
    ports:
      - "7000:80"
  db-server:
    image: sqlserver
    build:
      context: .
      dockerfile: sqlserver.Dockerfile
    volumes:
      - ./data:/var/opt/mssql/data 
    ports:
      - "1433:1433"
    networks: 
      - localdev

